[package]
name = "champlain"
repository = "https://github.com/alistair23/champlain"
version = "0.1.0"
authors = ["Alistair Francis <alistair@alistair23.me>"]
edition = "2018"

[dependencies]
libc = "0.2.0"
