[package]
name = "champlain"
repository = "https://github.com/alistair23/champlain"
version = "0.12.0"
authors = ["Alistair Francis <alistair@alistair23.me>"]
edition = "2018"

[dependencies]
libc = "0.2.0"
glib = "0.9.3"
glib-sys = "0.9.1"
gtk = "0.8.0"
